name: Your CICD Pipeline Name
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run pip install
      run: pip install -r requeriments.txt
    - name: run main script
      run: python main.py
